apiVersion: v1
data:
  POSTGRES_DB: linkset
  POSTGRES_USER: mohitd13
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: shortener
  labels:
    app: shortener
  annotations:
    argocd.argoproj.io/sync-wave: "1"
