apiVersion: v1
data:
  DESCRIPTION: A URL Shortener service to create unique codes for long URLs.
  POSTGRES_PORT: "5432"
  POSTGRES_SERVER: postgresql
  TITLE: URL Shortener
  VERSION: "1.0"
kind: ConfigMap
metadata:
  name: shortener-config
  namespace: shortener
  labels:
    app: shortener
  annotations:
    argo.argoproj.io/sync-wave: "1"
