apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cm.postgresql.yaml
- secret.postgresql.yaml
- svc.postgresql-headless.yaml
- sts.postgresql.yaml
- svc.postgresql.yaml
- cm.shortener.yaml
- deploy.shortener.yaml
- svc.shortener.yaml