apiVersion: v1
data:
  POSTGRES_PASSWORD: a1dOcG9kamRIS2FncXFHZQ==
kind: Secret
metadata:
  name: postgres-secret
  namespace: shortener
  labels:
    app: shortener
  annotations:
    argocd.argoproj.io/sync-wave: "1"
