apiVersion: v1
kind: Service
metadata:
  name: shortener
  namespace: shortener
  labels:
    app: shortener
    rel: canary
    tier: backend
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    app: shortener
    tier: backend
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
