apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: shortener
    ver: "1.0"
    rel: canary
    tier: database
  annotations:
    argo.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: shortener
    tier: database
  ports:
  - name: postgresdb
    port: 5432
    targetPort: postgresdb
    protocol: TCP
